spring:
  application:
    name: service-demo
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          issuer-uri: http://localhost:9000
          audiences:
            - oidc-client
      client:
        registration:
          service-demo:
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/service-demo
            scope: openid, profile
        provider:
          service-demo:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            user-name-attribute: sub

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE  # 추가