spring:
  profiles:
    active: local

  application:
    name: service-demo
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_URI}/oauth2/jwks
          issuer-uri: ${AUTH_SERVER_URI}
          audiences:
            - oidc-client
      client:
        registration:
          service-demo:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${APP_BASE_URI}/login/oauth2/code/service-demo
            scope: openid, read, write, profile
        provider:
          service-demo:
            authorization-uri: ${AUTH_SERVER_URI}/oauth2/authorize
            token-uri: ${AUTH_SERVER_URI}/oauth2/token
            user-info-uri: ${AUTH_SERVER_URI}/userinfo
            jwk-set-uri: ${AUTH_SERVER_URI}/oauth2/jwks
            user-name-attribute: sub

app:
  frontend-uri: ${FRONTEND_URI}