spring.application.name=service-demo

# Registration
#spring.security.oauth2.client.registration.service-demo.client-id=YOUR_CLIENT_ID
#spring.security.oauth2.client.registration.service-demo.client-secret=YOUR_CLIENT_SECRET
#spring.security.oauth2.client.registration.service-demo.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.service-demo.redirect-uri={baseUrl}/login/oauth2/code/service-demo
#spring.security.oauth2.client.registration.service-demo.scope=openid,profile

# Provider
#spring.security.oauth2.client.provider.service-demo.authorization-uri=https://AUTH_SERVER/oauth/authorize
#spring.security.oauth2.client.provider.service-demo.token-uri=https://AUTH_SERVER/oauth/token
#spring.security.oauth2.client.provider.service-demo.user-info-uri=https://AUTH_SERVER/userinfo
#spring.security.oauth2.client.provider.service-demo.user-name-attribute=sub